name: Error by trial.
favicon: null
layout_spectrum: 0.872683540917933
typography_spectrum: 0.6999451539013535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08460628497414291
  lightness: 0.4354868435766548
  saturation: 0.8329661830794066
  rhythmicContrast: 0.42531220871023834
purpose: []
